# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/nigelbreslaw/mister-magik-cross-armv7:ubuntu20-d047ace4d737"

[build.env]
volumes = ["MISTER_REPO_ROOT=../.."]
passthrough = [
    "FFMPEG_DIR",
    "CFLAGS",
    "HOST_CFLAGS",
    "CFLAGS_x86_64_unknown_linux_gnu",
    "MISTER_MAGIK_BUILD_NUMBER",
    "MISTER_MAGIK_BUILD_TIME",
    "MISTER_MAGIK_SOURCE_DIRTY",
    "MISTER_MAGIK_SOURCE_REVISION",
    "MISTER_MAGIK_VERSION",
    "MISTER_UI_BUILD_SCOPE",
    "PKG_CONFIG_PATH",
    "PKG_CONFIG_ALLOW_CROSS",
]
