// @generated by scripts/checks/generate-hdmi-evidence-protocol.py; do not edit.
// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

pub const HDMI_EVIDENCE_SCHEMA: u16 = 1;
pub const GET_HDMI_EVIDENCE: u16 = 0x60;
pub const HDMI_EVIDENCE_MAGIC: u16 = 0x4d50;
pub const HDMI_EVIDENCE_WORDS: usize = 4;

pub const HDMI_EVIDENCE_FLAG_LOCK_SEEN_HIGH: u16 = 1 << 0;
pub const HDMI_EVIDENCE_FLAG_LOCK_ARMED: u16 = 1 << 1;
pub const HDMI_EVIDENCE_FLAG_LOCK_CURRENT: u16 = 1 << 2;
pub const HDMI_EVIDENCE_FLAG_LOCK_EVER_LOST: u16 = 1 << 3;
pub const HDMI_EVIDENCE_FLAG_LOCK_LOSS_COUNT_OVERFLOW: u16 = 1 << 4;
pub const HDMI_EVIDENCE_FLAGS_MASK: u16 = 0x001f;

pub const HDMI_EVIDENCE_SCHEMA_WORD: usize = 0;
pub const HDMI_EVIDENCE_FLAGS_WORD: usize = 1;
pub const HDMI_EVIDENCE_LOCK_LOSS_COUNT_WORD: usize = 2;
pub const HDMI_EVIDENCE_CRC_WORD: usize = 3;
pub const HDMI_EVIDENCE_ZERO_GOLDEN_CRC: u16 = 0xf3a6;
