// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

export component AboutScreen inherits Rectangle {
    background: #0b0d14;
    VerticalLayout {
        padding: 48px;
        spacing: 24px;
        Text {
            text: "About";
            color: #06d6a0;
            font-size: 24px;
            horizontal-alignment: center;
        }
        Text {
            text: "MiSTer MagiK is an Unintuitive.com software production. Crafted with love in Finland by Nigel Breslaw.";
            color: #e8e0f0;
            font-size: 16px;
            wrap: word-wrap;
            horizontal-alignment: center;
        }
        Text {
            text: "Thanks to the MiSTer project for making all of this possible";
            color: #b8acc8;
            font-size: 16px;
            wrap: word-wrap;
            horizontal-alignment: center;
        }
        Text {
            text: "Made with Slint. Delivering beautiful UI's on the most challenging of hardware www.slint.dev";
            color: #70e1f5;
            font-size: 16px;
            wrap: word-wrap;
            horizontal-alignment: center;
        }
        Rectangle { vertical-stretch: 1; background: transparent; }
        Text { text: "B: back"; color: #6f8198; font-size: 8px; horizontal-alignment: center; }
    }

}
