version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/desktop"
      - "/framebuffer-stream"
      - "/magik-gui"
      - "/magik-gui/catalog"
      - "/magik-gui/ui-generated"
      - "/tools/magik-agent"
      - "/tools/mister"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/Helsinki"
    groups:
      rust-crates:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/Helsinki"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "rust-toolchain"
    directory: "/magik-gui"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/Helsinki"
    groups:
      rust-toolchain:
        patterns:
          - "*"
