// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

export enum PixelTextSize {
    px8,
    px16,
    px24,
    px32,
}

export global PixelText8Metrics {
    pure public function resolve(size: PixelTextSize) -> length {
        return size == PixelTextSize.px8 ? 8px
            : size == PixelTextSize.px16 ? 16px
            : size == PixelTextSize.px24 ? 24px
            : 32px;
    }
}

export component PixelText8 inherits Text {
    in property <PixelTextSize> size: PixelTextSize.px8;
    color: white;
    font-size: PixelText8Metrics.resolve(root.size);
    horizontal-alignment: start;
    vertical-alignment: top;
    overflow: clip;
    wrap: no-wrap;
}
