// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

export enum Spleen5x8Size {
    px8,
    px16,
}

export global Spleen5x8Metrics {
    pure public function resolve(size: Spleen5x8Size) -> length {
        return size == Spleen5x8Size.px8 ? 8px : 16px;
    }
}

export component Spleen5x8 inherits Text {
    in property <Spleen5x8Size> size: Spleen5x8Size.px8;
    color: white;
    font-family: "Spleen 5x8";
    font-size: Spleen5x8Metrics.resolve(root.size);
    horizontal-alignment: start;
    vertical-alignment: top;
    overflow: clip;
    wrap: no-wrap;
}
