// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

export enum Start2PSize {
    px8,
    px16,
    px24,
    px32,
}

export global Start2PMetrics {
    pure public function resolve(size: Start2PSize) -> length {
        return size == Start2PSize.px8 ? 8px
            : size == Start2PSize.px16 ? 16px
            : size == Start2PSize.px24 ? 24px
            : 32px;
    }
}

export component Start2P inherits Text {
    in property <Start2PSize> size: Start2PSize.px8;
    color: white;
    font-family: "Press Start 2P";
    font-size: Start2PMetrics.resolve(root.size);
    horizontal-alignment: start;
    vertical-alignment: top;
    overflow: clip;
    wrap: no-wrap;
}
