// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

pub mod copy;
pub mod damage;
#[cfg(feature = "ui")]
pub mod downsample;
pub mod format;
#[cfg(feature = "framebuffer-lab")]
pub mod hidden_latch;
pub mod hidden_scanout;
#[cfg(feature = "ui")]
pub mod mapped;
#[cfg(feature = "ui")]
pub mod mode;
pub mod ownership;
#[cfg(feature = "ui")]
pub mod present;
pub mod rgb565;
pub mod route;
#[cfg(feature = "ui")]
pub mod sample;
#[cfg(feature = "ui")]
pub mod scanout_slots;
#[cfg(feature = "ui")]
pub mod stream;
#[cfg(feature = "ui")]
pub mod target;
pub mod vertical_scale;
pub mod vsync;
