// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

import { MisterWindow, MisterUi } from "mister_window.slint";
export { MisterUi }
export { Spleen6x12Size } from "components/spleen_6x12.slint";
import { InputView } from "api.slint";
export { InputView }
import { ControllerPanel } from "controller_panel.slint";

export component ControllerTest inherits MisterWindow {
    title: "MiSTer Controller Test";
    background: #1a1424;

    ControllerPanel {
        width: 100%;
        height: 100%;
    }
}
