// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

import { MisterWindow, MisterUi } from "mister_window.slint";
import { MisterBridge, PreviewStatus, ScreenshotPackProgress } from "api.slint";
import { CrtLauncherUi } from "variants/crt_ui.slint";
import { HdmiLauncherUi } from "variants/hdmi_ui.slint";
import "fonts/PressStart2P-Regular.ttf";
import "fonts/PressStart2P-PAL288-Regular.ttf";
import "fonts/PressStart2P-PAL576-Regular.ttf";
import "fonts/LilliputSteps.otf";

export { MisterUi }
export { MisterBridge, PreviewStatus, ScreenshotPackProgress }
export { ArcadeGame } from "arcade_game.slint";
export { MenuItem, MenuItemKind } from "launcher_menu.slint";

export component Launcher inherits MisterWindow {
    default-font-family: "Press Start 2P";
    title: "MiSTer MagiK Launcher";
    background: MisterBridge.screen-mode == 0 ? #0b0d14 : #1a1424;

    if MisterUi.crt-layout : CrtLauncherUi { }
    if !MisterUi.crt-layout : HdmiLauncherUi { }
}
