import { MisterWindow, MisterUi } from "../mister_window.slint";
export { MisterUi }
import "../fonts/PressStart2P-Regular.ttf";

export component SolidFill inherits MisterWindow {
    background: #101018;
    default-font-family: "Press Start 2P";

    property <int> s: MisterUi.scale;
    property <duration> tick: animation-tick();
    property <int> phase: Math.mod(tick / 1ms, 3000) / 3000 * 4;

    Text {
        x: 32px * s;
        y: 16px * s;
        text: "bench: solid_fill";
        font-size: 24px * s;
        color: #ffffff;
    }

    Rectangle {
        x: 0;
        y: 50px * s;
        width: parent.width / 2;
        height: (parent.height - 50px * s) / 2;
        background: root.phase == 0 ? #ff0000 : (root.phase == 1 ? #cc0000 : #990000);
    }
    Rectangle {
        x: parent.width / 2;
        y: 50px * s;
        width: parent.width / 2;
        height: (parent.height - 50px * s) / 2;
        background: root.phase == 1 ? #00ff00 : (root.phase == 2 ? #00cc00 : #009900);
    }
    Rectangle {
        x: 0;
        y: 50px * s + (parent.height - 50px * s) / 2;
        width: parent.width / 2;
        height: (parent.height - 50px * s) / 2;
        background: root.phase == 2 ? #0000ff : (root.phase == 3 ? #0000cc : #000099);
    }
    Rectangle {
        x: parent.width / 2;
        y: 50px * s + (parent.height - 50px * s) / 2;
        width: parent.width / 2;
        height: (parent.height - 50px * s) / 2;
        background: root.phase == 3 ? #ffff00 : (root.phase == 0 ? #cccc00 : #999900);
    }

    Rectangle {
        x: 0;
        y: 50px * s;
        width: parent.width;
        height: 2px * s;
        background: #ffffff;
    }
}
