#!/bin/sh
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

# Stable MiSTer Scripts / Downloader entrypoint. Lifecycle policy lives in Rust.
set -eu

FAT="${MISTER_MAGIK_FAT:-/media/fat}"

fail() {
  echo "MiSTer MagiK: ERROR: $*" >&2
  exit 1
}

# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

# @generated by scripts/checks/generate-platform-v3-consumers.py; do not edit.
PLATFORM_V3_FORMAT='mister-magik-platform-v3'
PLATFORM_V3_FILE_NAME='platform-v3.manifest'
PLATFORM_V3_FIELD_NAMES='format platform_release platform_release_number platform_bundle_id qualification_candidate_id latch_protocol_version latch_capability_mask main_path gui_path manager_path scanout_module_path scanout_metadata_path latch_rbf_path latch_metadata_path main_sha256 gui_sha256 manager_sha256 scanout_module_sha256 scanout_metadata_sha256 latch_rbf_sha256 latch_metadata_sha256 platform_contract_sha256 main_revision magik_revision menu_revision'
PLATFORM_V3_PUBLIC_ROOT='/media/fat/mister-magik'
PLATFORM_V3_PUBLIC_MAIN='/media/fat/MiSTer_MagiK'
PLATFORM_V3_PUBLIC_GUI='/media/fat/mister-magik/mister-magik-fb'
PLATFORM_V3_PUBLIC_MANAGER='/media/fat/mister-magik/mister-magik-manager'
PLATFORM_V3_PUBLIC_SCANOUT_MODULE='/media/fat/mister-magik/mister_magik_scanout_slots.ko'
PLATFORM_V3_PUBLIC_SCANOUT_METADATA='/media/fat/mister-magik/mister_magik_scanout_slots.metadata.txt'
PLATFORM_V3_PUBLIC_LATCH_RBF='/media/fat/mister-magik/fpga/menu-magik-vblank-latch.rbf'
PLATFORM_V3_PUBLIC_LATCH_METADATA='/media/fat/mister-magik/fpga/menu-magik-vblank-latch.metadata.txt'
PLATFORM_V3_DEV_ROOT='/media/fat/mister-magik-dev'
PLATFORM_V3_DEV_MAIN='/media/fat/MiSTer_MagiKDev'
PLATFORM_V3_DEV_GUI='/media/fat/mister-magik-dev/mister-magik-fb'
PLATFORM_V3_DEV_MANAGER='/media/fat/mister-magik-dev/mister-magik-manager'
PLATFORM_V3_DEV_SCANOUT_MODULE='/media/fat/mister-magik-dev/mister_magik_scanout_slots.ko'
PLATFORM_V3_DEV_SCANOUT_METADATA='/media/fat/mister-magik-dev/mister_magik_scanout_slots.metadata.txt'
PLATFORM_V3_DEV_LATCH_RBF='/media/fat/mister-magik-dev/fpga/menu-magik-vblank-latch.rbf'
PLATFORM_V3_DEV_LATCH_METADATA='/media/fat/mister-magik-dev/fpga/menu-magik-vblank-latch.metadata.txt'

public_root="${PLATFORM_V3_PUBLIC_ROOT#/media/fat/}"
manager_relative="${PLATFORM_V3_PUBLIC_MANAGER#/media/fat/}"
[ "$public_root" != "$PLATFORM_V3_PUBLIC_ROOT" ] || fail "public root is outside /media/fat"
[ "$manager_relative" != "$PLATFORM_V3_PUBLIC_MANAGER" ] || \
  fail "public manager is outside /media/fat"
MANIFEST="$FAT/$public_root/$PLATFORM_V3_FILE_NAME"
MANAGER="$FAT/$manager_relative"

[ -r "$MANIFEST" ] || fail "missing $MANIFEST"
[ -f "$MANAGER" ] || fail "missing $MANAGER"
for tool in grep sed sha256sum awk chmod env; do
  command -v "$tool" >/dev/null 2>&1 || fail "required tool is unavailable: $tool"
done

manifest_value() {
  key="$1"
  count="$(grep -c "^$key=" "$MANIFEST" 2>/dev/null || true)"
  [ "$count" = 1 ] || return 1
  sed -n "s/^$key=//p" "$MANIFEST"
}

expected_fields=0
for key in $PLATFORM_V3_FIELD_NAMES; do
  manifest_value "$key" >/dev/null || fail "manifest has no unique $key"
  expected_fields=$((expected_fields + 1))
done
actual_fields="$(awk 'NF && substr($0,1,1) != "#" { if (index($0,"=") == 0) exit 2; count++ } END { print count + 0 }' "$MANIFEST")" || \
  fail "manifest contains a malformed field"
[ "$actual_fields" = "$expected_fields" ] || fail "manifest field set is not canonical"

manager_path="$(manifest_value manager_path)" || fail "manifest has no unique manager_path"
[ "$manager_path" = "$PLATFORM_V3_PUBLIC_MANAGER" ] || \
  fail "manifest manager_path is not canonical"
expected="$(manifest_value manager_sha256)" || fail "manifest has no unique manager_sha256"
case "$expected" in
  *[!0-9a-f]*|'') fail "manifest manager_sha256 is invalid" ;;
esac
[ "${#expected}" = 64 ] || fail "manifest manager_sha256 is invalid"
actual="$(sha256sum "$MANAGER" | awk '{print $1}')" || fail "cannot hash manager"
[ "$actual" = "$expected" ] || fail "manager hash mismatch"
chmod +x "$MANAGER" || fail "cannot make manager executable"

exec env MISTER_MAGIK_FAT="$FAT" \
  MISTER_MAGIK_INITTAB="${MISTER_MAGIK_INITTAB:-/etc/inittab}" \
  MISTER_MAGIK_TEST_MODE="${MISTER_MAGIK_TEST_MODE:-0}" \
  MISTER_MAGIK_TEST_OUTPUT_MODE="${MISTER_MAGIK_TEST_OUTPUT_MODE:-}" \
  MISTER_MAGIK_TEST_KEYS="${MISTER_MAGIK_TEST_KEYS:-}" \
  MISTER_MAGIK_DOWNLOADER="${MISTER_MAGIK_DOWNLOADER:-}" \
  MISTER_MAGIK_RECOVERY_MANAGER="${MISTER_MAGIK_RECOVERY_MANAGER:-}" \
  "$MANAGER" "$@"
