// @generated by scripts/checks/generate-latch-protocol.py; do not edit.
// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

pub const SET_FBUF_LATCH: u16 = 0x57;
pub const GET_FBUF_LATCH: u16 = 0x58;
pub const GET_FBUF_LATCH_CAPS: u16 = 0x59;
pub const LATCH_MAGIC: u16 = 0x4d47;
pub const STATUS_MAGIC: u16 = 0x4d48;
pub const CAPS_MAGIC: u16 = 0x4d49;
pub const ACTIVE_PROTOCOL_VERSION: u16 = 3;
pub const PROTOCOL_V2: u16 = 2;
pub const PROTOCOL_V3: u16 = 3;
pub const MAX_WIDTH: u16 = 1366;
pub const MAX_HEIGHT: u16 = 768;
pub const MAX_STRIDE_BYTES: u16 = 2736;

pub const CAP_RGB565: u16 = 1 << 0;
pub const CAP_DOUBLE_BUFFER: u16 = 1 << 1;
pub const CAP_VARIABLE_GEOMETRY: u16 = 1 << 2;
pub const CAP_TRANSACTIONAL_POST: u16 = 1 << 3;
pub const CAP_COHERENT_STATUS: u16 = 1 << 4;
pub const CAP_STATUS_CRC: u16 = 1 << 5;
pub const CAP_POST_CRC: u16 = 1 << 6;
pub const V2_CAPS_FLAGS: u16 = 0x0007;
pub const V3_CAPS_FLAGS: u16 = 0x007f;
pub const V2_CAPS_WORDS: usize = 5;
pub const V3_CAPS_WORDS: usize = 6;
pub const V2_SET_WORDS: usize = 11;
pub const V3_SET_WORDS: usize = 12;
pub const V2_STATUS_WORDS: usize = 11;
pub const V3_STATUS_WORDS: usize = 14;

pub const STATUS_ACTIVE_ENABLED: u16 = 0;
pub const STATUS_PENDING_ENABLED: u16 = 1;
pub const STATUS_PENDING: u16 = 2;
pub const STATUS_MAGIK_OWNERSHIP: u16 = 3;
pub const STATUS_REJECT_REASON_SHIFT: u16 = 4;
pub const STATUS_REJECT_REASON_WIDTH: u16 = 4;

pub const REJECT_NONE: u8 = 0;
pub const REJECT_MISSING_WORD: u8 = 1;
pub const REJECT_DUPLICATE_WORD: u8 = 2;
pub const REJECT_OUT_OF_ORDER: u8 = 3;
pub const REJECT_POST_CLOSE: u8 = 4;
pub const REJECT_BAD_CRC: u8 = 5;
pub const REJECT_INVALID_MODE: u8 = 6;
pub const REJECT_INVALID_BASE: u8 = 7;
pub const REJECT_INVALID_GEOMETRY: u8 = 8;
pub const REJECT_INVALID_STRIDE: u8 = 9;
pub const REJECT_INVALID_BOUNDS: u8 = 10;
pub const REJECT_ADDRESS_WRAP: u8 = 11;
pub const REJECT_RESTARTED: u8 = 12;
pub const REJECT_SHIFTED_WORD: u8 = 13;
pub const REJECT_RESERVED: u8 = 14;
pub const REJECT_INTERNAL: u8 = 15;

pub const CRC_POLYNOMIAL: u16 = 0x1021;
pub const CRC_INITIAL: u16 = 0xffff;
pub const CRC_FINAL_XOR: u16 = 0x0000;

#[rustfmt::skip]
pub const GOLDEN_CAPS_V3_PAYLOAD: [u16; 5] = [
    0x0003,
    0x007f,
    0x0556,
    0x0300,
    0x0ab0,
];
pub const GOLDEN_CAPS_V3_CRC: u16 = 0xaa2d;
#[rustfmt::skip]
pub const GOLDEN_SET_V3_PAYLOAD: [u16; 11] = [
    0x8014,
    0x9000,
    0x227e,
    0x03c0,
    0x021c,
    0x0000,
    0x03bf,
    0x0000,
    0x021b,
    0x0780,
    0x002a,
];
pub const GOLDEN_SET_V3_CRC: u16 = 0x8ef9;
#[rustfmt::skip]
pub const GOLDEN_STATUS_V3_PAYLOAD: [u16; 13] = [
    0x002a,
    0x002b,
    0x000f,
    0x0003,
    0x0004,
    0x0005,
    0x9000,
    0x227e,
    0x03c0,
    0x021c,
    0x0780,
    0x0007,
    0x0009,
];
pub const GOLDEN_STATUS_V3_CRC: u16 = 0x2775;
