// @generated by scripts/checks/generate-latch-protocol.py; do not edit.
// Copyright (C) 2026 Nigel Breslaw
// SPDX-License-Identifier: GPL-3.0-or-later

pub const SET_FBUF_LATCH: u16 = 0x57;
pub const GET_FBUF_LATCH: u16 = 0x58;
pub const GET_FBUF_LATCH_CAPS: u16 = 0x59;
pub const GET_FBUF_LATCH_DIAGNOSTICS: u16 = 0x5a;
pub const GET_FBUF_LATCH_RECEIPT: u16 = 0x5b;
pub const GET_FBUF_PRESENTATION_TELEMETRY: u16 = 0x5c;
pub const LATCH_MAGIC: u16 = 0x4d47;
pub const STATUS_MAGIC: u16 = 0x4d48;
pub const CAPS_MAGIC: u16 = 0x4d49;
pub const DIAGNOSTICS_MAGIC: u16 = 0x4d4a;
pub const RECEIPT_MAGIC: u16 = 0x4d4b;
pub const PRESENTATION_TELEMETRY_MAGIC: u16 = 0x4d4c;
pub const ACTIVE_PROTOCOL_VERSION: u16 = 5;
pub const PROTOCOL_V5: u16 = 5;
pub const MAX_WIDTH: u16 = 1366;
pub const MAX_HEIGHT: u16 = 768;
pub const MAX_STRIDE_BYTES: u16 = 2736;

pub const CAP_RGB565: u16 = 1 << 0;
pub const CAP_DOUBLE_BUFFER: u16 = 1 << 1;
pub const CAP_VARIABLE_GEOMETRY: u16 = 1 << 2;
pub const CAP_TRANSACTIONAL_POST: u16 = 1 << 3;
pub const CAP_COHERENT_STATUS: u16 = 1 << 4;
pub const CAP_STATUS_CRC: u16 = 1 << 5;
pub const CAP_POST_CRC: u16 = 1 << 6;
pub const CAP_REJECTION_CONTEXT: u16 = 1 << 7;
pub const CAP_AUTHORITATIVE_RECEIPT: u16 = 1 << 8;
pub const CAP_AUTHORITATIVE_PRESENTATION_TELEMETRY: u16 = 1 << 9;
pub const V5_CAPS_FLAGS: u16 = 0x03ff;
pub const V5_CAPS_WORDS: usize = 6;
pub const V5_SET_PAYLOAD_WORDS: usize = 11;
pub const V5_SET_WORDS: usize = 12;
pub const V5_STATUS_WORDS: usize = 16;
pub const V5_DIAGNOSTICS_WORDS: usize = 7;
pub const V5_RECEIPT_WORDS: usize = 11;
pub const V5_PRESENTATION_TELEMETRY_WORDS: usize = 11;

pub const RECEIPT_NONE: u16 = 0;
pub const RECEIPT_ACCEPTED: u16 = 1;
pub const RECEIPT_REJECTED: u16 = 2;

pub const STATUS_ACTIVE_ENABLED: u16 = 0;
pub const STATUS_PENDING_ENABLED: u16 = 1;
pub const STATUS_PENDING: u16 = 2;
pub const STATUS_MAGIK_OWNERSHIP: u16 = 3;
pub const STATUS_REJECT_REASON_SHIFT: u16 = 4;
pub const STATUS_REJECT_REASON_WIDTH: u16 = 4;

pub const REJECT_NONE: u8 = 0;
pub const REJECT_MISSING_WORD: u8 = 1;
pub const REJECT_DUPLICATE_WORD: u8 = 2;
pub const REJECT_OUT_OF_ORDER: u8 = 3;
pub const REJECT_POST_CLOSE: u8 = 4;
pub const REJECT_BAD_CRC: u8 = 5;
pub const REJECT_INVALID_MODE: u8 = 6;
pub const REJECT_INVALID_BASE: u8 = 7;
pub const REJECT_INVALID_GEOMETRY: u8 = 8;
pub const REJECT_INVALID_STRIDE: u8 = 9;
pub const REJECT_INVALID_BOUNDS: u8 = 10;
pub const REJECT_ADDRESS_WRAP: u8 = 11;
pub const REJECT_RESTARTED: u8 = 12;
pub const REJECT_SHIFTED_WORD: u8 = 13;
pub const REJECT_PENDING_BUSY: u8 = 14;
pub const REJECT_RESERVED: u8 = 15;

pub const CRC_POLYNOMIAL: u16 = 0x1021;
pub const CRC_INITIAL: u16 = 0xffff;
pub const CRC_FINAL_XOR: u16 = 0x0000;

#[rustfmt::skip]
pub const GOLDEN_CAPS_V5_PAYLOAD: [u16; 5] = [
    0x0005,
    0x03ff,
    0x0556,
    0x0300,
    0x0ab0,
];
pub const GOLDEN_CAPS_V5_CRC: u16 = 0x1c42;
#[rustfmt::skip]
pub const GOLDEN_SET_V5_PAYLOAD: [u16; 11] = [
    0x8014,
    0x9000,
    0x227e,
    0x03c0,
    0x021c,
    0x0000,
    0x03bf,
    0x0000,
    0x021b,
    0x0780,
    0x002b,
];
pub const GOLDEN_SET_V5_CRC: u16 = 0x1341;
#[rustfmt::skip]
pub const GOLDEN_STATUS_V5_PAYLOAD: [u16; 15] = [
    0x002a,
    0x002b,
    0x000f,
    0x0003,
    0x0004,
    0x9000,
    0x227e,
    0x03c0,
    0x021c,
    0x0780,
    0x0007,
    0x0009,
    0x0064,
    0x0065,
    0x0065,
];
pub const GOLDEN_STATUS_V5_CRC: u16 = 0x1ca6;
#[rustfmt::skip]
pub const GOLDEN_DIAGNOSTICS_V5_PAYLOAD: [u16; 6] = [
    0x0007,
    0x0001,
    0x000b,
    0x0000,
    0x0058,
    0x0000,
];
pub const GOLDEN_DIAGNOSTICS_V5_CRC: u16 = 0x4181;
#[rustfmt::skip]
pub const GOLDEN_RECEIPT_V5_PAYLOAD: [u16; 10] = [
    0x0065,
    0x002b,
    0x0001,
    0x0065,
    0x002b,
    0x0065,
    0x002b,
    0x0064,
    0x002a,
    0x0000,
];
pub const GOLDEN_RECEIPT_V5_CRC: u16 = 0x3d8a;
#[rustfmt::skip]
pub const GOLDEN_PRESENTATION_TELEMETRY_V5_PAYLOAD: [u16; 10] = [
    0x5678,
    0x1234,
    0x5670,
    0x1234,
    0x0008,
    0x0000,
    0x0003,
    0x0000,
    0x002a,
    0x0009,
];
pub const GOLDEN_PRESENTATION_TELEMETRY_V5_CRC: u16 = 0xe152;
