import { MisterWindow, MisterUi } from "mister_window.slint";
export { MisterUi }
import { MisterBridge } from "mister_bridge.slint";
import { ArcadeListScreen } from "arcade_list.slint";
export { MisterBridge }
export { ArcadeGame, GameSystem } from "arcade_game.slint";
import "fonts/PressStart2P-Regular.ttf";

export component ArcadePage inherits MisterWindow {
    default-font-family: "Press Start 2P";
    title: "MiSTer MagiK Arcade";
    background: #120d1a;

    ArcadeListScreen {
        width: parent.width;
        height: parent.height;
    }
}
