import { MisterWindow, MisterUi } from "mister_window.slint";
export { MisterUi }
import { MisterBridge } from "api.slint";
export { MisterBridge }
import { ControllerPanel } from "controller_panel.slint";
import "fonts/PressStart2P-Regular.ttf";

export component ControllerTest inherits MisterWindow {
    default-font-family: "Press Start 2P";
    title: "MiSTer Controller Test";
    background: #1a1424;

    ControllerPanel {
        width: 100%;
        height: 100%;
    }
}
