#!/usr/bin/env python3
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate Rust and SystemVerilog constants for HDMI evidence."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/hdmi-evidence-protocol.json"
RUST_PATH = ROOT / "mister/platform/contracts/video-diagnostics/src/generated_hdmi_evidence.rs"


def crc_word(crc: int, word: int, polynomial: int) -> int:
    for byte in ((word >> 8) & 0xFF, word & 0xFF):
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ polynomial) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def zero_golden_crc(record: dict, crc_spec: dict) -> int:
    crc = crc_spec["initial"]
    payload = [record["schema"], *([0] * (record["word_count"] - 2))]
    for word in (record["command"], record["schema"], len(payload), *payload):
        crc = crc_word(crc, word, crc_spec["polynomial"])
    return crc ^ crc_spec["final_xor"]


def render_rust(spec: dict) -> str:
    lines = [
        "// @generated by scripts/checks/generate-hdmi-evidence-protocol.py; do not edit.",
        "// Copyright (C) 2026 Nigel Breslaw",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        f"pub const HDMI_EVIDENCE_SCHEMA: u16 = {spec['schema']};",
        f"pub const GET_HDMI_EVIDENCE: u16 = 0x{spec['command']:02x};",
        f"pub const HDMI_EVIDENCE_MAGIC: u16 = 0x{spec['magic']:04x};",
        f"pub const HDMI_EVIDENCE_WORDS: usize = {spec['word_count']};",
        "",
    ]
    mask = 0
    for name, bit in spec["flags"].items():
        lines.append(f"pub const HDMI_EVIDENCE_FLAG_{name.upper()}: u16 = 1 << {bit};")
        mask |= 1 << bit
    lines.append(f"pub const HDMI_EVIDENCE_FLAGS_MASK: u16 = 0x{mask:04x};")
    lines.append("")
    for index, name in enumerate(spec["words"]):
        lines.append(f"pub const HDMI_EVIDENCE_{name.upper()}_WORD: usize = {index};")
    lines.append(
        f"pub const HDMI_EVIDENCE_ZERO_GOLDEN_CRC: u16 = 0x{zero_golden_crc(spec, spec['crc']):04x};"
    )
    activity = spec["output_activity"]
    lines.extend(
        [
            "",
            f"pub const HDMI_OUTPUT_ACTIVITY_SCHEMA: u16 = {activity['schema']};",
            f"pub const GET_HDMI_OUTPUT_ACTIVITY: u16 = 0x{activity['command']:02x};",
            f"pub const HDMI_OUTPUT_ACTIVITY_MAGIC: u16 = 0x{activity['magic']:04x};",
            f"pub const HDMI_OUTPUT_ACTIVITY_WORDS: usize = {activity['word_count']};",
            f"pub const HDMI_OUTPUT_ACTIVITY_COUNTER_BITS: u32 = {activity['counter_bits']};",
            f"pub const HDMI_OUTPUT_ACTIVITY_COUNTER_MASK: u16 = 0x{(1 << activity['counter_bits']) - 1:04x};",
            "",
        ]
    )
    mask = 0
    for name, bit in activity["flags"].items():
        lines.append(f"pub const HDMI_OUTPUT_ACTIVITY_FLAG_{name.upper()}: u16 = 1 << {bit};")
        mask |= 1 << bit
    lines.append(f"pub const HDMI_OUTPUT_ACTIVITY_FLAGS_MASK: u16 = 0x{mask:04x};")
    lines.append("")
    for index, name in enumerate(activity["words"]):
        lines.append(f"pub const HDMI_OUTPUT_ACTIVITY_{name.upper()}_WORD: usize = {index};")
    lines.append(
        "pub const HDMI_OUTPUT_ACTIVITY_ZERO_GOLDEN_CRC: u16 = "
        f"0x{zero_golden_crc(activity, spec['crc']):04x};"
    )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> None:
    current = path.read_text() if path.exists() else ""
    if current == expected:
        return
    if check:
        raise SystemExit(
            "".join(
                difflib.unified_diff(
                    current.splitlines(True),
                    expected.splitlines(True),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                )
            )
        )
    path.write_text(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    if len(spec["words"]) != spec["word_count"] or spec["words"][-1] != "crc":
        raise SystemExit("HDMI evidence layout must match word count and end in CRC")
    activity = spec["output_activity"]
    if len(activity["words"]) != activity["word_count"] or activity["words"][-1] != "crc":
        raise SystemExit("HDMI output activity layout must match word count and end in CRC")
    write_or_check(RUST_PATH, render_rust(spec), args.check)


if __name__ == "__main__":
    main()
