#!/usr/bin/env python3
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate Rust and SystemVerilog constants for passive video diagnostics."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/video-diagnostics-protocol.json"
HDMI_EVIDENCE_SPEC_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/hdmi-evidence-protocol.json"
RUST_PATH = ROOT / "mister/platform/contracts/video-diagnostics/src/generated.rs"
SV_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/mister_magik_video_diagnostics_protocol.svh"


def upper(value: str) -> str:
    return value.upper()


def crc_word(crc: int, word: int, polynomial: int) -> int:
    for byte in ((word >> 8) & 0xFF, word & 0xFF):
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ polynomial) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def message_crc(spec: dict, command: int, payload: list[int]) -> int:
    crc_spec = spec["crc"]
    crc = crc_spec["initial"]
    for word in (command, spec["schema"], len(payload), *payload):
        crc = crc_word(crc, word, crc_spec["polynomial"])
    return crc ^ crc_spec["final_xor"]


def render_rust(spec: dict) -> str:
    lines = [
        "// @generated by scripts/checks/generate-video-diagnostics-protocol.py; do not edit.",
        "// Copyright (C) 2026 Nigel Breslaw",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        f"pub const VIDEO_DIAGNOSTICS_SCHEMA: u16 = {spec['schema']};",
    ]
    for name, command in spec["commands"].items():
        lines.append(f"pub const GET_VIDEO_DIAGNOSTICS_{upper(name)}: u16 = 0x{command:02x};")
    for name, magic in spec["magic"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(name)}_MAGIC: u16 = 0x{magic:04x};")
    lines.append("")
    for name, count in spec["word_counts"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(name)}_WORDS: usize = {count};")
    lines.append("")
    for name, value in spec["states"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_STATE_{upper(name)}: u16 = {value};")
    for name, value in spec["domains"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_DOMAIN_{upper(name)}: u16 = {value};")
    for name, value in spec["dispositions"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_DISPOSITION_{upper(name)}: u16 = {value};")
    for name, value in spec["triggers"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_TRIGGER_{upper(name)}: u16 = {value};")
    for group, flags in spec["flags"].items():
        mask = 0x0003 if group == "state_flags" else 0
        for name, bit in flags.items():
            lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)}: u16 = 1 << {bit};")
            mask |= 1 << bit
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_MASK: u16 = 0x{mask:04x};")
    for group in ("control", "avalon", "output"):
        lines.append("")
        for index, name in enumerate(spec[f"{group}_words"]):
            lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)}: usize = {index};")
        payload = [spec["schema"], *([0] * (spec["word_counts"][group] - 2))]
        crc = message_crc(spec, spec["commands"][group], payload)
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_ZERO_GOLDEN_CRC: u16 = 0x{crc:04x};")
    return "\n".join(lines) + "\n"


def render_sv(spec: dict, hdmi_evidence: dict) -> str:
    lines = [
        "/* @generated by scripts/checks/generate-video-diagnostics-protocol.py; do not edit. */",
        "/* Copyright (C) 2026 Nigel Breslaw */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "",
        f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_SCHEMA = 16'd{spec['schema']};",
    ]
    for name, command in spec["commands"].items():
        lines.append(f"localparam [7:0] MAGIK_UIO_GET_VIDEO_DIAGNOSTICS_{upper(name)} = 8'h{command:02X};")
    for name, magic in spec["magic"].items():
        lines.append(f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(name)}_MAGIC = 16'h{magic:04X};")
    for name, count in spec["word_counts"].items():
        lines.append(f"localparam [5:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(name)}_WORDS = 6'd{count};")
    for name, value in spec["states"].items():
        lines.append(f"localparam [1:0] MAGIK_VIDEO_DIAGNOSTICS_STATE_{upper(name)} = 2'd{value};")
    for name, value in spec["triggers"].items():
        lines.append(f"localparam [7:0] MAGIK_VIDEO_DIAGNOSTICS_TRIGGER_{upper(name)} = 8'd{value};")
    for name, value in spec["dispositions"].items():
        lines.append(f"localparam [3:0] MAGIK_VIDEO_DIAGNOSTICS_DISPOSITION_{upper(name)} = 4'd{value};")
    for group, flags in spec["flags"].items():
        mask = 0x0003 if group == "state_flags" else 0
        for name, bit in flags.items():
            lines.append(f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)} = 16'h{1 << bit:04X};")
            mask |= 1 << bit
        lines.append(f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(group)}_MASK = 16'h{mask:04X};")
    for group in ("control", "avalon", "output"):
        lines.append("")
        for index, name in enumerate(spec[f"{group}_words"]):
            lines.append(f"localparam [5:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)} = 6'd{index};")
    lines.extend(
        [
            "",
            f"localparam [15:0] MAGIK_HDMI_EVIDENCE_SCHEMA = 16'd{hdmi_evidence['schema']};",
            f"localparam [7:0] MAGIK_UIO_GET_HDMI_EVIDENCE = 8'h{hdmi_evidence['command']:02X};",
            f"localparam [15:0] MAGIK_HDMI_EVIDENCE_MAGIC = 16'h{hdmi_evidence['magic']:04X};",
            f"localparam [2:0] MAGIK_HDMI_EVIDENCE_WORDS = 3'd{hdmi_evidence['word_count']};",
            f"localparam [15:0] MAGIK_HDMI_EVIDENCE_HEADER_CRC = 16'h{hdmi_evidence_header_crc(hdmi_evidence):04X};",
            "",
        ]
    )
    mask = 0
    for name, bit in hdmi_evidence["flags"].items():
        lines.append(
            f"localparam [15:0] MAGIK_HDMI_EVIDENCE_FLAG_{upper(name)} = 16'h{1 << bit:04X};"
        )
        mask |= 1 << bit
    lines.append(f"localparam [15:0] MAGIK_HDMI_EVIDENCE_FLAGS_MASK = 16'h{mask:04X};")
    lines.append("")
    for index, name in enumerate(hdmi_evidence["words"]):
        lines.append(f"localparam [1:0] MAGIK_HDMI_EVIDENCE_{upper(name)}_WORD = 2'd{index};")
    activity = hdmi_evidence["output_activity"]
    lines.extend(
        [
            "",
            f"localparam [15:0] MAGIK_HDMI_OUTPUT_ACTIVITY_SCHEMA = 16'd{activity['schema']};",
            f"localparam [7:0] MAGIK_UIO_GET_HDMI_OUTPUT_ACTIVITY = 8'h{activity['command']:02X};",
            f"localparam [15:0] MAGIK_HDMI_OUTPUT_ACTIVITY_MAGIC = 16'h{activity['magic']:04X};",
            f"localparam [2:0] MAGIK_HDMI_OUTPUT_ACTIVITY_WORDS = 3'd{activity['word_count']};",
            f"localparam [2:0] MAGIK_HDMI_OUTPUT_ACTIVITY_COUNTER_BITS = 3'd{activity['counter_bits']};",
            f"localparam [15:0] MAGIK_HDMI_OUTPUT_ACTIVITY_COUNTER_MASK = 16'h{(1 << activity['counter_bits']) - 1:04X};",
            f"localparam [15:0] MAGIK_HDMI_OUTPUT_ACTIVITY_HEADER_CRC = 16'h{hdmi_evidence_header_crc(activity, hdmi_evidence['crc']):04X};",
            "",
        ]
    )
    mask = 0
    for name, bit in activity["flags"].items():
        lines.append(
            f"localparam [15:0] MAGIK_HDMI_OUTPUT_ACTIVITY_FLAG_{upper(name)} = 16'h{1 << bit:04X};"
        )
        mask |= 1 << bit
    lines.append(f"localparam [15:0] MAGIK_HDMI_OUTPUT_ACTIVITY_FLAGS_MASK = 16'h{mask:04X};")
    lines.append("")
    for index, name in enumerate(activity["words"]):
        lines.append(
            f"localparam [2:0] MAGIK_HDMI_OUTPUT_ACTIVITY_{upper(name)}_WORD = 3'd{index};"
        )
    path_activity = hdmi_evidence["path_activity"]
    lines.extend(
        [
            "",
            f"localparam [2:0] MAGIK_HDMI_PATH_ACTIVITY_COUNTER_BITS = 3'd{path_activity['counter_bits']};",
            f"localparam [15:0] MAGIK_HDMI_PATH_ACTIVITY_COUNTER_MASK = 16'h{(1 << path_activity['counter_bits']) - 1:04X};",
        ]
    )
    for record_name, record in path_activity["records"].items():
        prefix = f"MAGIK_HDMI_{upper(record_name)}_ACTIVITY"
        lines.extend(
            [
                "",
                f"localparam [15:0] {prefix}_SCHEMA = 16'd{record['schema']};",
                f"localparam [7:0] MAGIK_UIO_GET_HDMI_{upper(record_name)}_ACTIVITY = 8'h{record['command']:02X};",
                f"localparam [15:0] {prefix}_MAGIC = 16'h{record['magic']:04X};",
                f"localparam [2:0] {prefix}_WORDS = 3'd{record['word_count']};",
                f"localparam [15:0] {prefix}_HEADER_CRC = 16'h{hdmi_evidence_header_crc(record, hdmi_evidence['crc']):04X};",
            ]
        )
        mask = 0
        for name, bit in record["flags"].items():
            lines.append(f"localparam [15:0] {prefix}_FLAG_{upper(name)} = 16'h{1 << bit:04X};")
            mask |= 1 << bit
        lines.append(f"localparam [15:0] {prefix}_FLAGS_MASK = 16'h{mask:04X};")
        for index, name in enumerate(record["words"]):
            lines.append(f"localparam [2:0] {prefix}_{upper(name)}_WORD = 3'd{index};")
        for word_name, mask in record.get("reserved_zero_masks", {}).items():
            lines.append(
                f"localparam [15:0] {prefix}_{upper(word_name)}_RESERVED_ZERO_MASK = 16'h{mask:04X};"
            )
        for name, offset in record["counters"].items():
            lines.append(f"localparam [5:0] {prefix}_{upper(name)}_BIT = 6'd{offset};")
        for name, field in record.get("fields", {}).items():
            lines.append(
                f"localparam [3:0] {prefix}_{upper(name)}_BIT = 4'd{field['bit']};"
            )
            lines.append(
                f"localparam [15:0] {prefix}_{upper(name)}_MASK = 16'h{((1 << field['width']) - 1):04X};"
            )
    scheduler = hdmi_evidence["scaler_scheduler_state"]
    prefix = "MAGIK_SCALER_SCHEDULER_STATE"
    lines.extend(
        [
            "",
            f"localparam [15:0] {prefix}_SCHEMA = 16'd{scheduler['schema']};",
            f"localparam [7:0] MAGIK_UIO_GET_SCALER_SCHEDULER_STATE = 8'h{scheduler['command']:02X};",
            f"localparam [15:0] {prefix}_MAGIC = 16'h{scheduler['magic']:04X};",
            f"localparam [1:0] {prefix}_WORDS = 2'd{scheduler['word_count']};",
            f"localparam [15:0] {prefix}_HEADER_CRC = 16'h{hdmi_evidence_header_crc(scheduler, hdmi_evidence['crc']):04X};",
        ]
    )
    for index, name in enumerate(scheduler["words"]):
        lines.append(f"localparam [1:0] {prefix}_{upper(name)}_WORD = 2'd{index};")
    for name, field in scheduler["fields"].items():
        lines.append(f"localparam [3:0] {prefix}_{upper(name)}_BIT = 4'd{field['bit']};")
        lines.append(
            f"localparam [15:0] {prefix}_{upper(name)}_MASK = 16'h{((1 << field['width']) - 1):04X};"
        )
    return "\n".join(lines) + "\n"


def hdmi_evidence_header_crc(record: dict, crc_spec: dict | None = None) -> int:
    crc_spec = record["crc"] if crc_spec is None else crc_spec
    crc = crc_spec["initial"]
    for word in (record["command"], record["schema"], record["word_count"] - 1):
        crc = crc_word(crc, word, crc_spec["polynomial"])
    return crc


def write_or_check(path: Path, expected: str, check: bool) -> None:
    current = path.read_text() if path.exists() else ""
    if current == expected:
        return
    if check:
        raise SystemExit("".join(difflib.unified_diff(current.splitlines(True), expected.splitlines(True), fromfile=str(path), tofile=f"{path} (generated)")))
    path.write_text(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    hdmi_evidence = json.loads(HDMI_EVIDENCE_SPEC_PATH.read_text())
    for group in ("control", "avalon", "output"):
        if len(spec[f"{group}_words"]) != spec["word_counts"][group]:
            raise SystemExit(f"{group} word layout does not match word count")
        if spec[f"{group}_words"][-1] != "crc":
            raise SystemExit(f"{group} response must end in CRC")
    for name, record in hdmi_evidence["path_activity"]["records"].items():
        for word_name, mask in record.get("reserved_zero_masks", {}).items():
            if word_name not in record["words"]:
                raise SystemExit(f"HDMI {name} reserved-zero mask names an unknown word")
            if mask < 0 or mask > 0xffff:
                raise SystemExit(f"HDMI {name} reserved-zero mask is outside one word")
            for field_name, field in record.get("fields", {}).items():
                if field["word"] == word_name:
                    field_mask = ((1 << field["width"]) - 1) << field["bit"]
                    if field_mask & mask:
                        raise SystemExit(
                            f"HDMI {name} field {field_name} overlaps reserved-zero bits"
                        )
    write_or_check(RUST_PATH, render_rust(spec), args.check)
    write_or_check(SV_PATH, render_sv(spec, hdmi_evidence), args.check)


if __name__ == "__main__":
    main()
