#!/usr/bin/env python3
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate Rust and SystemVerilog constants for HDMI evidence."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/hdmi-evidence-protocol.json"
RUST_PATH = ROOT / "mister/platform/contracts/video-diagnostics/src/generated_hdmi_evidence.rs"


def crc_word(crc: int, word: int, polynomial: int) -> int:
    for byte in ((word >> 8) & 0xFF, word & 0xFF):
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ polynomial) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def zero_golden_crc(record: dict, crc_spec: dict) -> int:
    crc = crc_spec["initial"]
    payload = [record["schema"], *([0] * (record["word_count"] - 2))]
    for word in (record["command"], record["schema"], len(payload), *payload):
        crc = crc_word(crc, word, crc_spec["polynomial"])
    return crc ^ crc_spec["final_xor"]


def render_rust(spec: dict) -> str:
    lines = [
        "// @generated by scripts/checks/generate-hdmi-evidence-protocol.py; do not edit.",
        "// Copyright (C) 2026 Nigel Breslaw",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        f"pub const HDMI_EVIDENCE_SCHEMA: u16 = {spec['schema']};",
        f"pub const GET_HDMI_EVIDENCE: u16 = 0x{spec['command']:02x};",
        f"pub const HDMI_EVIDENCE_MAGIC: u16 = 0x{spec['magic']:04x};",
        f"pub const HDMI_EVIDENCE_WORDS: usize = {spec['word_count']};",
        "",
    ]
    mask = 0
    for name, bit in spec["flags"].items():
        lines.append(f"pub const HDMI_EVIDENCE_FLAG_{name.upper()}: u16 = 1 << {bit};")
        mask |= 1 << bit
    lines.append(f"pub const HDMI_EVIDENCE_FLAGS_MASK: u16 = 0x{mask:04x};")
    lines.append("")
    for index, name in enumerate(spec["words"]):
        lines.append(f"pub const HDMI_EVIDENCE_{name.upper()}_WORD: usize = {index};")
    lines.append(
        f"pub const HDMI_EVIDENCE_ZERO_GOLDEN_CRC: u16 = 0x{zero_golden_crc(spec, spec['crc']):04x};"
    )
    activity = spec["output_activity"]
    lines.extend(
        [
            "",
            f"pub const HDMI_OUTPUT_ACTIVITY_SCHEMA: u16 = {activity['schema']};",
            f"pub const GET_HDMI_OUTPUT_ACTIVITY: u16 = 0x{activity['command']:02x};",
            f"pub const HDMI_OUTPUT_ACTIVITY_MAGIC: u16 = 0x{activity['magic']:04x};",
            f"pub const HDMI_OUTPUT_ACTIVITY_WORDS: usize = {activity['word_count']};",
            f"pub const HDMI_OUTPUT_ACTIVITY_COUNTER_BITS: u32 = {activity['counter_bits']};",
            f"pub const HDMI_OUTPUT_ACTIVITY_COUNTER_MASK: u16 = 0x{(1 << activity['counter_bits']) - 1:04x};",
            "",
        ]
    )
    mask = 0
    for name, bit in activity["flags"].items():
        lines.append(f"pub const HDMI_OUTPUT_ACTIVITY_FLAG_{name.upper()}: u16 = 1 << {bit};")
        mask |= 1 << bit
    lines.append(f"pub const HDMI_OUTPUT_ACTIVITY_FLAGS_MASK: u16 = 0x{mask:04x};")
    lines.append("")
    for index, name in enumerate(activity["words"]):
        lines.append(f"pub const HDMI_OUTPUT_ACTIVITY_{name.upper()}_WORD: usize = {index};")
    lines.append(
        "pub const HDMI_OUTPUT_ACTIVITY_ZERO_GOLDEN_CRC: u16 = "
        f"0x{zero_golden_crc(activity, spec['crc']):04x};"
    )
    path_activity = spec["path_activity"]
    lines.extend(
        [
            "",
            f"pub const HDMI_PATH_ACTIVITY_COUNTER_BITS: u32 = {path_activity['counter_bits']};",
            f"pub const HDMI_PATH_ACTIVITY_COUNTER_MASK: u16 = 0x{(1 << path_activity['counter_bits']) - 1:04x};",
        ]
    )
    for record_name, record in path_activity["records"].items():
        prefix = f"HDMI_{record_name.upper()}_ACTIVITY"
        command_name = f"GET_HDMI_{record_name.upper()}_ACTIVITY"
        lines.extend(
            [
                "",
                f"pub const {prefix}_SCHEMA: u16 = {record['schema']};",
                f"pub const {command_name}: u16 = 0x{record['command']:02x};",
                f"pub const {prefix}_MAGIC: u16 = 0x{record['magic']:04x};",
                f"pub const {prefix}_WORDS: usize = {record['word_count']};",
            ]
        )
        mask = 0
        for name, bit in record["flags"].items():
            lines.append(f"pub const {prefix}_FLAG_{name.upper()}: u16 = 1 << {bit};")
            mask |= 1 << bit
        lines.append(f"pub const {prefix}_FLAGS_MASK: u16 = 0x{mask:04x};")
        for index, name in enumerate(record["words"]):
            lines.append(f"pub const {prefix}_{name.upper()}_WORD: usize = {index};")
        for word_name, mask in record.get("reserved_zero_masks", {}).items():
            lines.append(
                f"pub const {prefix}_{word_name.upper()}_RESERVED_ZERO_MASK: u16 = 0x{mask:04x};"
            )
        for name, offset in record["counters"].items():
            lines.append(f"pub const {prefix}_{name.upper()}_BIT: usize = {offset};")
        for name, field in record.get("fields", {}).items():
            word_name = field["word"].upper()
            word_constant = f"{prefix}_{name.upper()}_WORD"
            word_value = f"{prefix}_{word_name}_WORD"
            declaration = f"pub const {word_constant}: usize = {word_value};"
            if len(declaration) > 100:
                lines.extend((f"pub const {word_constant}: usize =", f"    {word_value};"))
            else:
                lines.append(declaration)
            lines.append(f"pub const {prefix}_{name.upper()}_BIT: usize = {field['bit']};")
            lines.append(
                f"pub const {prefix}_{name.upper()}_MASK: u16 = 0x{((1 << field['width']) - 1):04x};"
            )
        lines.append(
            f"pub const {prefix}_ZERO_GOLDEN_CRC: u16 = "
            f"0x{zero_golden_crc(record, spec['crc']):04x};"
        )
    raw_scaler = spec["raw_scaler_state"]
    lines.extend(
        [
            "",
            f"pub const RAW_SCALER_STATE_SCHEMA: u16 = {raw_scaler['schema']};",
            f"pub const GET_RAW_SCALER_STATE: u16 = 0x{raw_scaler['command']:02x};",
            f"pub const RAW_SCALER_STATE_MAGIC: u16 = 0x{raw_scaler['magic']:04x};",
            f"pub const RAW_SCALER_STATE_WORDS: usize = {raw_scaler['word_count']};",
        ]
    )
    for index, name in enumerate(raw_scaler["words"]):
        lines.append(f"pub const RAW_SCALER_STATE_{name.upper()}_WORD: usize = {index};")
    mask = 0
    for name, bit in raw_scaler.get("flags", {}).items():
        lines.append(f"pub const RAW_SCALER_STATE_FLAG_{name.upper()}: u16 = 1 << {bit};")
        mask |= 1 << bit
    lines.append(f"pub const RAW_SCALER_STATE_FLAGS_MASK: u16 = 0x{mask:04x};")
    for word_name, reserved_mask in raw_scaler.get("reserved_zero_masks", {}).items():
        lines.append(
            f"pub const RAW_SCALER_STATE_{word_name.upper()}_RESERVED_ZERO_MASK: u16 = "
            f"0x{reserved_mask:04x};"
        )
    lines.append(
        "pub const RAW_SCALER_STATE_ZERO_GOLDEN_CRC: u16 = "
        f"0x{zero_golden_crc(raw_scaler, spec['crc']):04x};"
    )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> None:
    current = path.read_text() if path.exists() else ""
    if current == expected:
        return
    if check:
        raise SystemExit(
            "".join(
                difflib.unified_diff(
                    current.splitlines(True),
                    expected.splitlines(True),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                )
            )
        )
    path.write_text(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    if len(spec["words"]) != spec["word_count"] or spec["words"][-1] != "crc":
        raise SystemExit("HDMI evidence layout must match word count and end in CRC")
    activity = spec["output_activity"]
    if len(activity["words"]) != activity["word_count"] or activity["words"][-1] != "crc":
        raise SystemExit("HDMI output activity layout must match word count and end in CRC")
    path_activity = spec["path_activity"]
    commands = {spec["command"], activity["command"]}
    magics = {spec["magic"], activity["magic"]}
    for name, record in path_activity["records"].items():
        if len(record["words"]) != record["word_count"] or record["words"][-1] != "crc":
            raise SystemExit(f"HDMI {name} layout must match word count and end in CRC")
        if record["command"] in commands or record["magic"] in magics:
            raise SystemExit(f"HDMI {name} command or magic overlaps another record")
        commands.add(record["command"])
        magics.add(record["magic"])
        for counter, offset in record["counters"].items():
            if offset < 0 or offset + path_activity["counter_bits"] > 32:
                raise SystemExit(f"HDMI {name} counter {counter} is outside two packed words")
        for field_name, field in record.get("fields", {}).items():
            if field["word"] not in record["words"]:
                raise SystemExit(f"HDMI {name} field {field_name} names an unknown word")
            if field["bit"] < 0 or field["width"] <= 0 or field["bit"] + field["width"] > 16:
                raise SystemExit(f"HDMI {name} field {field_name} is outside one word")
        for word_name, mask in record.get("reserved_zero_masks", {}).items():
            if word_name not in record["words"]:
                raise SystemExit(f"HDMI {name} reserved-zero mask names an unknown word")
            if mask < 0 or mask > 0xffff:
                raise SystemExit(f"HDMI {name} reserved-zero mask is outside one word")
            for field_name, field in record.get("fields", {}).items():
                if field["word"] == word_name:
                    field_mask = ((1 << field["width"]) - 1) << field["bit"]
                    if field_mask & mask:
                        raise SystemExit(
                            f"HDMI {name} field {field_name} overlaps reserved-zero bits"
                    )
    raw_scaler = spec["raw_scaler_state"]
    if len(raw_scaler["words"]) != raw_scaler["word_count"] or raw_scaler["words"][-1] != "crc":
        raise SystemExit("raw scaler state layout must match word count and end in CRC")
    if raw_scaler["command"] in commands or raw_scaler["magic"] in magics:
        raise SystemExit("raw scaler state command or magic overlaps another record")
    used_mask = 0
    for flag_name, bit in raw_scaler.get("flags", {}).items():
        if bit < 0 or bit > 15 or used_mask & (1 << bit):
            raise SystemExit(f"raw scaler state flag {flag_name} is invalid or overlaps")
        used_mask |= 1 << bit
    for word_name, mask in raw_scaler.get("reserved_zero_masks", {}).items():
        if word_name not in raw_scaler["words"] or mask < 0 or mask > 0xffff:
            raise SystemExit(f"raw scaler state reserved mask {word_name} is invalid")
        if word_name == "flags" and mask & used_mask:
            raise SystemExit("raw scaler state flag and reserved masks overlap")
    write_or_check(RUST_PATH, render_rust(spec), args.check)


if __name__ == "__main__":
    main()
