#!/usr/bin/env python3
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate checked-in non-Rust platform-v3 constants and golden fixtures."""

from __future__ import annotations

import argparse
import hashlib
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "mister/platform/contracts/platform-v3.schema.toml"
OUTPUT = ROOT / "mister/platform/contracts/generated"
COMPONENTS = (
    "main",
    "gui",
    "manager",
    "scanout_module",
    "scanout_metadata",
    "latch_rbf",
    "latch_metadata",
)


def shell_value(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def constants(schema: dict[str, object]) -> str:
    lines = [
        "# Copyright (C) 2026 Nigel Breslaw",
        "# SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        "# @generated by scripts/checks/generate-platform-v3-consumers.py; do not edit.",
        f"PLATFORM_V3_FORMAT={shell_value(str(schema['manifest_format']))}",
        f"PLATFORM_V3_FILE_NAME={shell_value(str(schema['file_name']))}",
        f"PLATFORM_V3_FIELD_NAMES={shell_value(' '.join(schema['fields']))}",
    ]
    layouts = schema["layouts"]
    assert isinstance(layouts, dict)
    for layout_name in ("public", "dev"):
        layout = layouts[layout_name]
        assert isinstance(layout, dict)
        prefix = f"PLATFORM_V3_{layout_name.upper()}"
        for name in ("root", *COMPONENTS):
            lines.append(f"{prefix}_{name.upper()}={shell_value(str(layout[name]))}")
    return "\n".join(lines) + "\n"


def fixture(schema: dict[str, object], layout_name: str) -> str:
    fields = schema["fields"]
    layouts = schema["layouts"]
    assert isinstance(fields, list)
    assert isinstance(layouts, dict)
    layout = layouts[layout_name]
    assert isinstance(layout, dict)
    values = {
        "format": str(schema["manifest_format"]),
        "platform_release": "platform-v0.16",
        "platform_release_number": "16",
        "platform_bundle_id": "c" * 64,
        "latch_protocol_version": str(schema["latch_protocol_version"]),
        "latch_capability_mask": str(schema["latch_capability_mask"]),
        "platform_contract_sha256": "d" * 64,
        "main_revision": "b" * 40,
        "magik_revision": "b" * 40,
        "menu_revision": "b" * 40,
    }
    for component in COMPONENTS:
        values[f"{component}_path"] = str(layout[component])
        values[f"{component}_sha256"] = "a" * 64
    candidate = hashlib.sha256()
    for field in fields:
        if field != "qualification_candidate_id":
            candidate.update(f"{field}={values[field]}\n".encode())
    values["qualification_candidate_id"] = candidate.hexdigest()
    return "".join(f"{field}={values[field]}\n" for field in fields)


def generated_files() -> dict[Path, str]:
    schema = tomllib.loads(SCHEMA.read_text())
    if schema.get("format") != "mister-magik-platform-v3-schema-v1":
        raise SystemExit("unsupported platform-v3 schema")
    return {
        ROOT / "scripts/MiSTer-MagiK.sh": (
            ROOT / "scripts/templates/MiSTer-MagiK.sh.in"
        )
        .read_text()
        .replace("@PLATFORM_CONSTANTS@", constants(schema).rstrip()),
        OUTPUT / "platform-v3.constants.sh": constants(schema),
        OUTPUT / "platform-v3.public.fixture": fixture(schema, "public"),
        OUTPUT / "platform-v3.development.fixture": fixture(schema, "dev"),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in generated_files().items():
        if args.check:
            if not path.is_file() or path.read_text() != expected:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
    if stale:
        raise SystemExit(
            "stale generated platform-v3 consumer: " + ", ".join(map(str, stale))
        )


if __name__ == "__main__":
    main()
