#!/usr/bin/env python3
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the Rust and SystemVerilog latch wire-contract constants."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/latch-protocol.json"
RUST_PATH = ROOT / "mister/platform/contracts/latch/src/generated.rs"
SV_PATH = (
    ROOT / "mister/platform/fpga/menu-vblank-latch/mister_magik_latch_protocol.svh"
)


def rust_name(value: str) -> str:
    return value.upper()


def render_rust(spec: dict) -> str:
    commands = spec["commands"]
    magic = spec["magic"]
    limits = spec["limits"]
    protocols = spec["protocols"]
    capabilities = spec["capabilities"]
    flags = spec["status_flags"]
    rejections = spec["rejection_reasons"]
    crc = spec["crc"]
    goldens = spec["goldens"]
    lines = [
        "// @generated by scripts/checks/generate-latch-protocol.py; do not edit.",
        "// Copyright (C) 2026 Nigel Breslaw",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        f"pub const SET_FBUF_LATCH: u16 = 0x{commands['set']:02x};",
        f"pub const GET_FBUF_LATCH: u16 = 0x{commands['get']:02x};",
        f"pub const GET_FBUF_LATCH_CAPS: u16 = 0x{commands['caps']:02x};",
        f"pub const GET_FBUF_LATCH_DIAGNOSTICS: u16 = 0x{commands['diagnostics']:02x};",
        f"pub const GET_FBUF_LATCH_RECEIPT: u16 = 0x{commands['receipt']:02x};",
        f"pub const GET_FBUF_PRESENTATION_TELEMETRY: u16 = 0x{commands['presentation_telemetry']:02x};",
        f"pub const LATCH_MAGIC: u16 = 0x{magic['set']:04x};",
        f"pub const STATUS_MAGIC: u16 = 0x{magic['status']:04x};",
        f"pub const CAPS_MAGIC: u16 = 0x{magic['caps']:04x};",
        f"pub const DIAGNOSTICS_MAGIC: u16 = 0x{magic['diagnostics']:04x};",
        f"pub const RECEIPT_MAGIC: u16 = 0x{magic['receipt']:04x};",
        f"pub const PRESENTATION_TELEMETRY_MAGIC: u16 = 0x{magic['presentation_telemetry']:04x};",
        f"pub const ACTIVE_PROTOCOL_VERSION: u16 = {spec['active_protocol_version']};",
        "pub const PROTOCOL_V5: u16 = 5;",
        f"pub const MAX_WIDTH: u16 = {limits['max_width']};",
        f"pub const MAX_HEIGHT: u16 = {limits['max_height']};",
        f"pub const MAX_STRIDE_BYTES: u16 = {limits['max_stride_bytes']};",
        "",
    ]
    for name, bit in capabilities.items():
        lines.append(f"pub const CAP_{rust_name(name)}: u16 = 1 << {bit};")
    lines.extend(
        [
            f"pub const V5_CAPS_FLAGS: u16 = 0x{protocols['5']['flags']:04x};",
            f"pub const V5_CAPS_WORDS: usize = {protocols['5']['caps_words']};",
            f"pub const V5_SET_PAYLOAD_WORDS: usize = {protocols['5']['set_payload_words']};",
            f"pub const V5_SET_WORDS: usize = {protocols['5']['set_words']};",
            f"pub const V5_STATUS_WORDS: usize = {protocols['5']['status_words']};",
            f"pub const V5_DIAGNOSTICS_WORDS: usize = {protocols['5']['diagnostics_words']};",
            f"pub const V5_RECEIPT_WORDS: usize = {protocols['5']['receipt_words']};",
            f"pub const V5_PRESENTATION_TELEMETRY_WORDS: usize = {protocols['5']['presentation_telemetry_words']};",
            "",
        ]
    )
    for name, value in spec["receipt_dispositions"].items():
        lines.append(f"pub const RECEIPT_{rust_name(name)}: u16 = {value};")
    lines.append("")
    for name, bit in flags.items():
        lines.append(f"pub const STATUS_{rust_name(name)}: u16 = {bit};")
    lines.append("")
    for name, value in rejections.items():
        lines.append(f"pub const REJECT_{rust_name(name)}: u8 = {value};")
    lines.extend(
        [
            "",
            f"pub const CRC_POLYNOMIAL: u16 = 0x{crc['polynomial']:04x};",
            f"pub const CRC_INITIAL: u16 = 0x{crc['initial']:04x};",
            f"pub const CRC_FINAL_XOR: u16 = 0x{crc['final_xor']:04x};",
            "",
        ]
    )
    for name, golden in goldens.items():
        upper = rust_name(name)
        lines.append("#[rustfmt::skip]")
        lines.append(
            f"pub const GOLDEN_{upper}_PAYLOAD: [u16; {len(golden['payload'])}] = ["
        )
        lines.extend(f"    0x{word:04x}," for word in golden["payload"])
        lines.append("];")
        lines.append(f"pub const GOLDEN_{upper}_CRC: u16 = 0x{golden['crc']:04x};")
    return "\n".join(lines) + "\n"


def render_sv(spec: dict) -> str:
    commands = spec["commands"]
    magic = spec["magic"]
    limits = spec["limits"]
    protocols = spec["protocols"]
    capabilities = spec["capabilities"]
    flags = spec["status_flags"]
    rejections = spec["rejection_reasons"]
    crc = spec["crc"]
    goldens = spec["goldens"]
    lines = [
        "/* @generated by scripts/checks/generate-latch-protocol.py; do not edit. */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "/* Copyright (C) 2026 Nigel Breslaw */",
        "",
        f"localparam [7:0]  MAGIK_UIO_SET_FBUF_LATCH = 8'h{commands['set']:02X};",
        f"localparam [7:0]  MAGIK_UIO_GET_FBUF_LATCH = 8'h{commands['get']:02X};",
        f"localparam [7:0]  MAGIK_UIO_GET_FBUF_LATCH_CAPS = 8'h{commands['caps']:02X};",
        f"localparam [7:0]  MAGIK_UIO_GET_FBUF_LATCH_DIAGNOSTICS = 8'h{commands['diagnostics']:02X};",
        f"localparam [7:0]  MAGIK_UIO_GET_FBUF_LATCH_RECEIPT = 8'h{commands['receipt']:02X};",
        f"localparam [7:0]  MAGIK_UIO_GET_FBUF_PRESENTATION_TELEMETRY = 8'h{commands['presentation_telemetry']:02X};",
        f"localparam [15:0] MAGIK_FBUF_LATCH_MAGIC = 16'h{magic['set']:04X};",
        f"localparam [15:0] MAGIK_FBUF_STATUS_MAGIC = 16'h{magic['status']:04X};",
        f"localparam [15:0] MAGIK_FBUF_CAPS_MAGIC = 16'h{magic['caps']:04X};",
        f"localparam [15:0] MAGIK_FBUF_DIAGNOSTICS_MAGIC = 16'h{magic['diagnostics']:04X};",
        f"localparam [15:0] MAGIK_FBUF_RECEIPT_MAGIC = 16'h{magic['receipt']:04X};",
        f"localparam [15:0] MAGIK_FBUF_PRESENTATION_TELEMETRY_MAGIC = 16'h{magic['presentation_telemetry']:04X};",
        f"localparam [15:0] MAGIK_FBUF_PROTOCOL_VERSION = 16'd{spec['active_protocol_version']};",
        "localparam [15:0] MAGIK_FBUF_PROTOCOL_V5 = 16'd5;",
        f"localparam [15:0] MAGIK_FBUF_CAPS_FLAGS = 16'h{protocols[str(spec['active_protocol_version'])]['flags']:04X};",
        f"localparam [15:0] MAGIK_FBUF_MAX_WIDTH = 16'd{limits['max_width']};",
        f"localparam [15:0] MAGIK_FBUF_MAX_HEIGHT = 16'd{limits['max_height']};",
        f"localparam [15:0] MAGIK_FBUF_MAX_STRIDE = 16'd{limits['max_stride_bytes']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_CAPS_WORDS = 5'd{protocols['5']['caps_words']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_SET_PAYLOAD_WORDS = 5'd{protocols['5']['set_payload_words']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_SET_WORDS = 5'd{protocols['5']['set_words']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_STATUS_WORDS = 5'd{protocols['5']['status_words']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_DIAGNOSTICS_WORDS = 5'd{protocols['5']['diagnostics_words']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_RECEIPT_WORDS = 5'd{protocols['5']['receipt_words']};",
        f"localparam [4:0]  MAGIK_FBUF_V5_PRESENTATION_TELEMETRY_WORDS = 5'd{protocols['5']['presentation_telemetry_words']};",
        "",
    ]
    for name, value in spec["receipt_dispositions"].items():
        lines.append(
            f"localparam [15:0] MAGIK_RECEIPT_{rust_name(name)} = 16'd{value};"
        )
    lines.append("")
    for name, bit in capabilities.items():
        lines.append(
            f"localparam [15:0] MAGIK_CAP_{rust_name(name)} = 16'h{1 << bit:04X};"
        )
    lines.append("")
    for name, bit in flags.items():
        lines.append(f"localparam integer MAGIK_STATUS_{rust_name(name)} = {bit};")
    lines.append("")
    for name, value in rejections.items():
        lines.append(f"localparam [3:0] MAGIK_REJECT_{rust_name(name)} = 4'd{value};")
    lines.extend(
        [
            "",
            f"localparam [15:0] MAGIK_CRC_POLYNOMIAL = 16'h{crc['polynomial']:04X};",
            f"localparam [15:0] MAGIK_CRC_INITIAL = 16'h{crc['initial']:04X};",
            f"localparam [15:0] MAGIK_CRC_FINAL_XOR = 16'h{crc['final_xor']:04X};",
        ]
    )
    for name, golden in goldens.items():
        upper = rust_name(name)
        lines.append("")
        for index, word in enumerate(golden["payload"]):
            lines.append(
                f"localparam [15:0] MAGIK_GOLDEN_{upper}_{index} = 16'h{word:04X};"
            )
        lines.append(
            f"localparam [15:0] MAGIK_GOLDEN_{upper}_CRC = 16'h{golden['crc']:04X};"
        )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> None:
    current = path.read_text() if path.exists() else ""
    if current == expected:
        return
    if check:
        diff = "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(path),
                tofile=f"{path} (generated)",
            )
        )
        raise SystemExit(diff or f"{path}: generated content differs")
    path.write_text(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    write_or_check(RUST_PATH, render_rust(spec), args.check)
    write_or_check(SV_PATH, render_sv(spec), args.check)


if __name__ == "__main__":
    main()
