#!/usr/bin/env python3
# Copyright (C) 2026 Nigel Breslaw
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate Rust and SystemVerilog constants for passive video diagnostics."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/video-diagnostics-protocol.json"
RUST_PATH = ROOT / "mister/platform/contracts/video-diagnostics/src/generated.rs"
SV_PATH = ROOT / "mister/platform/fpga/menu-vblank-latch/mister_magik_video_diagnostics_protocol.svh"


def upper(value: str) -> str:
    return value.upper()


def crc_word(crc: int, word: int, polynomial: int) -> int:
    for byte in ((word >> 8) & 0xFF, word & 0xFF):
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ polynomial) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def message_crc(spec: dict, command: int, payload: list[int]) -> int:
    crc_spec = spec["crc"]
    crc = crc_spec["initial"]
    for word in (command, spec["schema"], len(payload), *payload):
        crc = crc_word(crc, word, crc_spec["polynomial"])
    return crc ^ crc_spec["final_xor"]


def render_rust(spec: dict) -> str:
    lines = [
        "// @generated by scripts/checks/generate-video-diagnostics-protocol.py; do not edit.",
        "// Copyright (C) 2026 Nigel Breslaw",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        f"pub const VIDEO_DIAGNOSTICS_SCHEMA: u16 = {spec['schema']};",
    ]
    for name, command in spec["commands"].items():
        lines.append(f"pub const GET_VIDEO_DIAGNOSTICS_{upper(name)}: u16 = 0x{command:02x};")
    for name, magic in spec["magic"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(name)}_MAGIC: u16 = 0x{magic:04x};")
    lines.append("")
    for name, count in spec["word_counts"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(name)}_WORDS: usize = {count};")
    lines.append("")
    for name, value in spec["states"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_STATE_{upper(name)}: u16 = {value};")
    for name, value in spec["domains"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_DOMAIN_{upper(name)}: u16 = {value};")
    for name, value in spec["dispositions"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_DISPOSITION_{upper(name)}: u16 = {value};")
    for name, value in spec["triggers"].items():
        lines.append(f"pub const VIDEO_DIAGNOSTICS_TRIGGER_{upper(name)}: u16 = {value};")
    for group, flags in spec["flags"].items():
        mask = 0x0003 if group == "state_flags" else 0
        for name, bit in flags.items():
            lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)}: u16 = 1 << {bit};")
            mask |= 1 << bit
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_MASK: u16 = 0x{mask:04x};")
    for group in ("control", "avalon", "output"):
        lines.append("")
        for index, name in enumerate(spec[f"{group}_words"]):
            lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)}: usize = {index};")
        payload = [spec["schema"], *([0] * (spec["word_counts"][group] - 2))]
        crc = message_crc(spec, spec["commands"][group], payload)
        lines.append(f"pub const VIDEO_DIAGNOSTICS_{upper(group)}_ZERO_GOLDEN_CRC: u16 = 0x{crc:04x};")
    return "\n".join(lines) + "\n"


def render_sv(spec: dict) -> str:
    lines = [
        "/* @generated by scripts/checks/generate-video-diagnostics-protocol.py; do not edit. */",
        "/* Copyright (C) 2026 Nigel Breslaw */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "",
        f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_SCHEMA = 16'd{spec['schema']};",
    ]
    for name, command in spec["commands"].items():
        lines.append(f"localparam [7:0] MAGIK_UIO_GET_VIDEO_DIAGNOSTICS_{upper(name)} = 8'h{command:02X};")
    for name, magic in spec["magic"].items():
        lines.append(f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(name)}_MAGIC = 16'h{magic:04X};")
    for name, count in spec["word_counts"].items():
        lines.append(f"localparam [5:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(name)}_WORDS = 6'd{count};")
    for name, value in spec["states"].items():
        lines.append(f"localparam [1:0] MAGIK_VIDEO_DIAGNOSTICS_STATE_{upper(name)} = 2'd{value};")
    for name, value in spec["triggers"].items():
        lines.append(f"localparam [7:0] MAGIK_VIDEO_DIAGNOSTICS_TRIGGER_{upper(name)} = 8'd{value};")
    for name, value in spec["dispositions"].items():
        lines.append(f"localparam [3:0] MAGIK_VIDEO_DIAGNOSTICS_DISPOSITION_{upper(name)} = 4'd{value};")
    for group, flags in spec["flags"].items():
        mask = 0x0003 if group == "state_flags" else 0
        for name, bit in flags.items():
            lines.append(f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)} = 16'h{1 << bit:04X};")
            mask |= 1 << bit
        lines.append(f"localparam [15:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(group)}_MASK = 16'h{mask:04X};")
    for group in ("control", "avalon", "output"):
        lines.append("")
        for index, name in enumerate(spec[f"{group}_words"]):
            lines.append(f"localparam [5:0] MAGIK_VIDEO_DIAGNOSTICS_{upper(group)}_{upper(name)} = 6'd{index};")
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> None:
    current = path.read_text() if path.exists() else ""
    if current == expected:
        return
    if check:
        raise SystemExit("".join(difflib.unified_diff(current.splitlines(True), expected.splitlines(True), fromfile=str(path), tofile=f"{path} (generated)")))
    path.write_text(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    for group in ("control", "avalon", "output"):
        if len(spec[f"{group}_words"]) != spec["word_counts"][group]:
            raise SystemExit(f"{group} word layout does not match word count")
        if spec[f"{group}_words"][-1] != "crc":
            raise SystemExit(f"{group} response must end in CRC")
    write_or_check(RUST_PATH, render_rust(spec), args.check)
    write_or_check(SV_PATH, render_sv(spec), args.check)


if __name__ == "__main__":
    main()
